language: node_js

node_js:
   "8.9.4"

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
 - yarn lint
 - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  email: ritwickdey@outlook.com
  name: Ritwick Dey
  target-branch: master
  on:
    branch: development
